// samples/chaincode/tourofheroes/src/app/app.component.ts
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import { Component } from "@angular/core";

@Component({
    selector: "app-root",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.css"],
})
export class AppComponent {
    title = "Tour of Heroes";
}

// samples/chaincode/drawer/src/app.tsx
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import * as React from 'react';
import { DrawerCommandBar } from './drawerCommandBar';
import { DocumentList } from "./documentList";

export const App: React.FunctionComponent = () => {
    return (
        <div>
            <DrawerCommandBar />

            <DocumentList />
        </div>
    );
};
