// samples/chaincode/drawer/src/app.tsx
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import * as React from 'react';
import { DrawerCommandBar } from './drawerCommandBar';
import { DocumentList } from "./documentList";

export const App: React.FunctionComponent = () => {
    return (
        <div>
            <DrawerCommandBar />

            <DocumentList />
        </div>
    );
};

// samples/experiments/legacy/server/src/ng/app.component.ts
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import { Component } from "@angular/core";

@Component({
    selector: "my-app",
    styleUrls: ["stylesheets/app.component.css"],
    templateUrl: "templates/app.component.html",
})
export class AppComponent {
    public url = "/documents/calendar";
}
