// components/experimental/clicker-vue/src/index.tsx
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import Vue from "vue";
import {
    PrimedComponentFactory,
} from "@fluidframework/aqueduct";
// TODO: Move SyncedComponent to its own package to avoid a dependency on the ff/react package
// This is the only remaining mention of "react" in here
import { SyncedComponent } from "@fluidframework/react";
import { SharedCounter } from "@fluidframework/counter";
import { renderVue } from "@fluidframework/vue";
import Component from "vue-class-component";

// The props used by the Vue view component. This will automatically be filled by Fluid with the
// interface defined ICounterState
const VueProps = Vue.extend({
    props: {
        counter: Object,
    },
});

// A clicker implementation written using Vue that is powered by a SharedCounter
@Component
export class CounterVue extends VueProps {
    render(createElement) {
        return createElement("div",
            [
                createElement("span", this.counter.value),
                createElement("button",
                    {
                        on: {
                            click: () => {
                                this.counter.increment(1);
                            },
                        },
                    },
                    "+",
                ),
            ]);
    }
}

// The state definition powering the Vue view component. This is defined in SyncedComponent
// by the setConfig call in the constructor
interface ICounterState {
    counter?: SharedCounter;
}

/**
 * Basic ClickerVue example showing Clicker as a React Vue component
 */
export class ClickerVue extends SyncedComponent {
    constructor(props) {
        super(props);
        this.setConfig<ICounterState>(
            "clicker-vue",
            {
                syncedStateId: "clicker-vue",
                fluidToView:  new Map([
                    [
                        "counter", {
                            type: SharedCounter.name,
                            viewKey: "counter",
                            sharedObjectCreate: SharedCounter.create,
                            listenedEvents: ["incremented"],
                        },
                    ],
                ]),
                defaultViewState: {},
            },
        );
    }

    /**
     * Will return a new ClickerVue view
     */
    public render(div: HTMLElement) {
        renderVue(div, this, "clicker-vue", CounterVue);
        return div;
    }
}

// ----- FACTORY SETUP -----
export const ClickerVueInstantiationFactory = new PrimedComponentFactory(
    "clicker-vue",
    ClickerVue,
    [SharedCounter.getFactory()],
    {},
);
export const fluidExport = ClickerVueInstantiationFactory;

// examples/data-objects/clicker-react/clicker-reducer/src/index.tsx
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import {
    DataObjectFactory,
} from "@fluidframework/aqueduct";
import {
    IFluidReducerProps,
    IViewState,
    useReducerFluid,
    FluidStateUpdateFunction,
    IFluidDataProps,
    IFluidState,
    IFluidReducer,
    SyncedDataObject,
} from "@fluidframework/react";
import { SharedCounter } from "@fluidframework/counter";
import * as React from "react";
import * as ReactDOM from "react-dom";

// ---- React Functional Component w/ useReducer ----

interface ICounterReducerViewState extends IViewState {
    value: number;
}

interface ICounterReducerFluidState
    extends IFluidState {
    counter: SharedCounter;
}

interface IActionReducer
    extends IFluidReducer<
    ICounterReducerViewState,
    ICounterReducerFluidState,
    IFluidDataProps
    > {
    increment: FluidStateUpdateFunction<
    ICounterReducerViewState,
    ICounterReducerFluidState,
    IFluidDataProps
    >;
}

export const ActionReducer: IActionReducer = {
    increment: {
        function: (state, step: number) => {
            if (state === undefined || state.fluidState?.counter === undefined) {
                throw Error("State was not initialized prior to dispatch call");
            }
            const counter = state.fluidState?.counter;
            counter.increment(step);
            state.viewState.value = counter.value;
            return { state };
        },
    },
};

function CounterReactFunctionalReducer(
    props: IFluidReducerProps<
    ICounterReducerViewState,
    ICounterReducerFluidState,
    IActionReducer,
    {},
    IFluidDataProps
    >,
) {
    const [state, dispatch] = useReducerFluid(props, { value: 0 });

    return (
        <div>
            <span className="value">
                {state.viewState.value}
            </span>
            <button
                onClick={() => {
                    dispatch.increment.function(state, 1);
                }}
            >
                +
            </button>
            <button
                onClick={() => {
                    dispatch.increment.function(state, 2);
                }}
            >
                ++
            </button>
        </div>
    );
}

/**
 * ClickerReducer example using the useReducerFluid hook
 */
export class ClickerReducer extends SyncedDataObject {
    constructor(props) {
        super(props);

        this.setFluidConfig<ICounterReducerViewState,ICounterReducerFluidState>(
            "counter-reducer",
            {
                syncedStateId: "counter-reducer",
                fluidToView:  new Map([
                    [
                        "counter", {
                            type: SharedCounter.name,
                            viewKey: "value",
                            viewConverter: (viewState, fluidState) => {
                                return {
                                    value: fluidState.counter?.value,
                                };
                            },
                            sharedObjectCreate: SharedCounter.create,
                            listenedEvents: ["incremented"],
                        },
                    ],
                ]),
                viewToFluid: new Map([
                    [
                        "value", {
                            type: "number",
                            fluidKey: "counter",
                            fluidConverter: (viewState, fluidState) => {
                                return fluidState.counter?.value;
                            },
                        },
                    ],
                ]),
                defaultViewState: { value: 0 },
            },
        );
    }
    /**
     * Will return a new ClickerReducer view
     */
    public render(div: HTMLElement) {
        ReactDOM.render(
            <div>
                <CounterReactFunctionalReducer
                    syncedStateId={"counter-reducer"}
                    syncedDataObject={this}
                    reducer={ActionReducer}
                    selector={{}}
                />
            </div>,
            div,
        );
        return div;
    }

    // #endregion IFluidHTMLView
}

// ----- FACTORY SETUP -----
export const ClickerReducerInstantiationFactory = new DataObjectFactory(
    "clicker-reducer",
    ClickerReducer,
    [SharedCounter.getFactory()],
    {},
);
export const fluidExport = ClickerReducerInstantiationFactory;
